import math

class DifferentialDrivePID:
    """
    Tier 3: The PID Kinematics Controller (The Muscles) & Artificial Potential Fields
    
    This takes a Target Waypoint (X, Y) generated by the RL Brain or YOLO,
    uses APF to bend the path around walls, and then calculates the exact 
    motor PWMs to drive smoothly to that coordinate.
    """
    
    def __init__(self, kp_linear=0.8, kd_linear=0.1, kp_angular=1.5, kd_angular=0.2):
        self.kp_linear = kp_linear
        self.kd_linear = kd_linear
        self.kp_angular = kp_angular
        self.kd_angular = kd_angular
        
        self.prev_error_linear = 0.0
        self.prev_error_angular = 0.0

    def apply_potential_fields(self, current_x, current_y, current_theta, target_x, target_y, us_dists, laser_cm):
        """
        ARTIFICIAL POTENTIAL FIELDS (APF)
        Bends the target waypoint away from obstacles (Repulsive Forces).
        us_dists = [FL, FR, BL, BR] in meters.
        laser_cm = distance in cm.
        """
        # 1. Attractive Force (Pull towards the target)
        # We cap the attractive pull so it doesn't overpower the walls if the target is far
        dx = target_x - current_x
        dy = target_y - current_y
        dist_to_target = math.hypot(dx, dy)
        
        # Normalize the attractive vector to a max strength of 1.0
        if dist_to_target > 0.01:
            attr_x = (dx / dist_to_target)
            attr_y = (dy / dist_to_target)
        else:
            attr_x, attr_y = 0.0, 0.0

        # 2. Repulsive Forces (Push away from walls)
        rep_x = 0.0
        rep_y = 0.0
        
        # Define sensor mounting angles relative to the robot's heading (current_theta)
        # FL: +30 deg, FR: -30 deg, BL: +150 deg, BR: -150 deg, Laser: 0 deg
        sensor_angles = [
            current_theta + math.radians(30),   # Front Left
            current_theta - math.radians(30),   # Front Right
            current_theta + math.radians(150),  # Back Left
            current_theta - math.radians(150),  # Back Right
            current_theta                       # Laser (Front Center)
        ]
        
        # Convert distances to meters. If distance is > 0.4m (40cm), we ignore it (no repulsion).
        # We assume us_dists is in meters, laser_cm is in cm.
        distances = [
            us_dists[0], 
            us_dists[1], 
            us_dists[2], 
            us_dists[3], 
            laser_cm / 100.0
        ]
        
        REPULSION_STRENGTH = 0.15 # Tuning constant
        SAFE_DISTANCE = 0.40 # 40cm
        
        for i in range(5):
            dist = distances[i]
            if dist < SAFE_DISTANCE and dist > 0.01: # Avoid division by zero
                # The closer the wall, the stronger the push!
                push_force = REPULSION_STRENGTH * ((1.0 / dist) - (1.0 / SAFE_DISTANCE))
                
                # Push AWAY from the wall (angle + 180 degrees)
                push_angle = sensor_angles[i] + math.pi
                
                rep_x += push_force * math.cos(push_angle)
                rep_y += push_force * math.sin(push_angle)
                
        # 3. Sum the Forces (Attractive + Repulsive)
        final_x = attr_x + rep_x
        final_y = attr_y + rep_y
        
        # 4. Generate the new "Safe" Waypoint
        # We place it 10cm away from the robot in the direction of the final force vector
        safe_angle = math.atan2(final_y, final_x)
        safe_target_x = current_x + (0.1 * math.cos(safe_angle))
        safe_target_y = current_y + (0.1 * math.sin(safe_angle))
        
        return safe_target_x, safe_target_y


    def calculate_motor_speeds(self, current_x, current_y, current_theta, target_x, target_y):
        """
        Calculates the perfect Left and Right PWM speeds to reach the target coordinate.
        """
        # 1. Linear Error
        distance_error = math.hypot(target_x - current_x, target_y - current_y)
        
        # 2. Angle to Target
        angle_to_target = math.atan2(target_y - current_y, target_x - current_x)
        
        # 3. Angular Error (keep between -PI and +PI)
        angular_error = angle_to_target - current_theta
        angular_error = (angular_error + math.pi) % (2 * math.pi) - math.pi
        
        # 4. PID for Forward Velocity (V)
        linear_derivative = distance_error - self.prev_error_linear
        v = (self.kp_linear * distance_error) + (self.kd_linear * linear_derivative)
        
        # 5. PID for Angular Velocity (Omega)
        angular_derivative = angular_error - self.prev_error_angular
        omega = (self.kp_angular * angular_error) + (self.kd_angular * angular_derivative)
        
        # 6. Safety Limits
        if abs(angular_error) > math.radians(45):
            v = 0.0  # Stop driving forward, just spin to face it!
            
        v = max(-0.8, min(v, 0.8))
        omega = max(-0.8, min(omega, 0.8))
        
        # 7. Differential Kinematics
        left_pwm = v - (omega / 2.0)
        right_pwm = v + (omega / 2.0)
        
        left_pwm = max(-1.0, min(left_pwm, 1.0))
        right_pwm = max(-1.0, min(right_pwm, 1.0))
        
        self.prev_error_linear = distance_error
        self.prev_error_angular = angular_error
        
        return left_pwm, right_pwm
